### ISSUE TITLE
Flannel cni remaining on edge

### ISSUE THREAD

**Issue by duyanghao** [FabEdge/fabedge#170]
**Describe the bug**
There is still flannel cni remaining on edge when fabedge take effects.

**To Reproduce**
1. Deploy superedge with cloud-0 and edge-0.
2. Label nodes and deploy fabedge.
3. Add another edge-1 to superedge.
4. Label edge-1 to join fabedge network.
5. There flannel cni remaining on edge-1.

```
$ ip r
...
192.168.1.0/24 dev cni0 proto kernel scope link src 192.168.1.1 
192.168.1.0/24 dev br-fabedge proto kernel scope link src 192.168.1.1 
```

and env-prepares scripts output below:
```
+ find /etc/cni/net.d/ -type f -not -name fabedge.conf -exec rm '{}' ';'
+ cp -f /usr/local/bin/bridge /usr/local/bin/host-local /usr/local/bin/loopback /opt/cni/bin
+ ip link delete cni0
ip: can't find device 'cni0'
+ ip link delete flannel.1
ip: can't find device 'flannel.1'
+ ip route
+ grep flannel
+ read dst via gw others
+ iptables -t nat -F POSTROUTING
+ exit 0
```

**Environments**
Centos 7.8

**Expected behavior**
No flannel cni remains on edge when fabedge takes over edge network.

**Comment by haotaogeng** [comment]
I can not reproduced it in my env. I will keep an eye on this bug. thanks for report it.
