### ISSUE TITLE
[CNCF] Review the Online Programs Guidelines

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#302]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md

**Comment by haotaogeng** [comment]
Yes. I have reviewed the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
