### ISSUE TITLE
[CNCF] Understand the services available for your project at CNCF

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#303]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [[CNCF onboarding issue](https://github.com/cncf/toc/issues/798)](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/

**Comment by haotaogeng** [comment]
Yes. I understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
