### ISSUE TITLE
[CNCF] Understand the project proposal process and reqs

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#304]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction

**Comment by haotaogeng** [comment]
Yes. I  understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
