### ISSUE TITLE
[CNCF] Understand the trademark guidelines

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#305]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/

**Comment by haotaogeng** [comment]
Yes. I understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
