### ISSUE TITLE
[CNCF] Is your project in its own separate neutral github organization?

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#306]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Is your project in its own separate neutral github organization?

**Comment by Jinglun-Shang** [comment]
Please see this -> https://github.com/FabEdge

I think FabEdge is in its own separate, independent and neural GitHub organization.

**Comment by haotaogeng** [comment]
Yes. FabEdge is in its own separate neutral github organization with contributors from some different organizations.
