### ISSUE TITLE
[CNCF] Artwork, FabEdge logo updating

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#307]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

**Comment by haotaogeng** [comment]
PR is submitted.
https://github.com/cncf/artwork/pull/334

**Comment by haotaogeng** [comment]
Done
