### ISSUE TITLE
[CNCF] Understand the license allowlist

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#309]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist

**Comment by haotaogeng** [comment]
Yes. I understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
