### ISSUE TITLE
[CNCF] Is your project working on written, open governance?

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#310]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/

**Comment by haotaogeng** [comment]
Yes. FabEdge is working on the open governance:  https://contribute.cncf.io/maintainers/governance/
