### ISSUE TITLE
[CNCF] Are your slack channels migrated to the Kubernetes or CNCF Slack?

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#311]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)

**Comment by haotaogeng** [comment]
Yes. the slack channels created in CNCF Slack. https://cloud-native.slack.com/archives/C03AD0TFPFF

**Comment by haotaogeng** [comment]
Done
