### ISSUE TITLE
[CNCF] Submitted a Pull request to add your project as a sandbox project

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#312]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/

**Comment by haotaogeng** [comment]
FabEdge has been added.
https://github.com/cncf/landscape/pull/2379
