### ISSUE TITLE
[CNCF] Maintainer list + PR

### ISSUE THREAD

**Issue by Jinglun-Shang** [FabEdge/fabedge#313]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/798) that this issue will track:*

- [ ] Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it.

**Comment by haotaogeng** [comment]
PR is submitted:
https://github.com/cncf/foundation/pull/323

**Comment by haotaogeng** [comment]
Done
