### ISSUE TITLE
Cloud agent leads to infinite growth of IP rules

### ISSUE THREAD

**Issue by fei922** [FabEdge/fabedge#386]
**Describe the bug**

The IP rules of cloud agent nodes have increased by approximately 400 records in 14 hours. I don't know if this will have an impact on the operating system

![image](https://github.com/FabEdge/fabedge/assets/9672023/25111183-dadf-4a61-99ae-2f34571ab279)

fabedge version: v0.8.0
os version: ubuntu 16.04

**Comment by fei922** [comment]
![image](https://github.com/FabEdge/fabedge/assets/9672023/ff34980a-cbaf-4224-a198-cfdf10b76cc3)
Found this issue with ubuntu, but there is no issue with Centos

**Comment by bluven** [comment]
Thanks for your reporting, I'll try reproducing it on ubuntu.
