### ISSUE TITLE
[Question] What features have support? 

### ISSUE THREAD

**Issue by khalid-jobs** [FabEdge/fabedge#8]
According to the https://github.com/FabEdge/fabedge/blob/main/docs/roadmap.md, what features have support now? 1. the communication between edge pods 2. the communication between edge node and cloud node

**Comment by haotaogeng** [comment]
these features are ok now.   "edge node" refers to the node running kubeedge edgecore service.
-------------------------------------------
边缘节点，IPV4支持
  边缘pod和云端pod通讯 
  相同community里，边缘pod和边缘pod通讯
  边缘pod就近访问本地服务实例
  边缘pod访问云端服务实例

**Comment by khalid-davis** [comment]
Can you provide some examples to tell us roughly how to use it? Or the way to use it is exactly the same as the k8s native service. And your community is a new concept. It would be better to provide an example of how to use it.

**Comment by khalid-davis** [comment]
@haotaogeng

**Comment by haotaogeng** [comment]
> Can you provide some examples to tell us roughly how to use it? Or the way to use it is exactly the same as the k8s native service. And your community is a new concept. It would be better to provide an example of how to use it.

1）service is exactly the same as before.    2) community is a CRD to define which edge nodes can communicate directly,  then fabedge will establish the tunnels between them. Pls. note, it is not well tested yet and I will provide some example later.

**Comment by khalid-davis** [comment]
OK ,thanks.

**Comment by haotaogeng** [comment]
we add a doc: docs/how-to-use-community.md for "community" example.
