### ISSUE TITLE
secrets "tokensecret" not found

### ISSUE THREAD

**Issue by Haomeng** [FabEdge/fabedge#96]
按照https://github.com/FabEdge/fabedge/blob/main/docs/install_k8s.md 文档第二部添加k8s边缘节点时候出错 add-edge-node.sh   ，debug了一下，应该是找不到tokensecret 
[root@ubuntu ansible]#  kubectl get secret -nkubeedge tokensecret
Error from server (NotFound): secrets "tokensecret" not found
[root@ubuntu ansible]#

![image](https://user-images.githubusercontent.com/5365082/132952210-b4ae543c-0a45-413e-9e99-edac46f0d04a.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by haotaogeng** [comment]
It has been identified due to the environment issue (insufficient h/w resource).
